- name: Install postgres repository key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- name: Install postgres repository
  apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main" state=present

- name: Install postgres client
  apt: pkg="postgresql-client-{{ postgres_version }},libpq-dev" state=latest
