---
- name: install puma upstart script
  template: src=puma_upstart.conf.j2 dest=/etc/init/puma_{{ deploy_rails_puma_application }}.conf owner={{ deploy_rails_puma_user }} group={{ deploy_rails_puma_user }} mode=0644
